/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSolicitacoesRouteImport } from './routes/_authenticated/solicitacoes'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedAtividadesRouteImport } from './routes/_authenticated/atividades'
import { Route as AuthenticatedAplicacoesRouteImport } from './routes/_authenticated/aplicacoes'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAplicacoesSlugRouteImport } from './routes/_authenticated/aplicacoes.$slug'
import { Route as AuthenticatedAdminEmpresasRouteImport } from './routes/_authenticated/admin.empresas'
import { Route as AuthenticatedAdminComunicadosRouteImport } from './routes/_authenticated/admin.comunicados'
import { Route as AuthenticatedAdminAplicacoesRouteImport } from './routes/_authenticated/admin.aplicacoes'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSolicitacoesRoute =
  AuthenticatedSolicitacoesRouteImport.update({
    id: '/solicitacoes',
    path: '/solicitacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAtividadesRoute = AuthenticatedAtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAplicacoesRoute = AuthenticatedAplicacoesRouteImport.update({
  id: '/aplicacoes',
  path: '/aplicacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAplicacoesSlugRoute =
  AuthenticatedAplicacoesSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedAplicacoesRoute,
  } as any)
const AuthenticatedAdminEmpresasRoute =
  AuthenticatedAdminEmpresasRouteImport.update({
    id: '/empresas',
    path: '/empresas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminComunicadosRoute =
  AuthenticatedAdminComunicadosRouteImport.update({
    id: '/comunicados',
    path: '/comunicados',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAplicacoesRoute =
  AuthenticatedAdminAplicacoesRouteImport.update({
    id: '/aplicacoes',
    path: '/aplicacoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/aplicacoes': typeof AuthenticatedAplicacoesRouteWithChildren
  '/atividades': typeof AuthenticatedAtividadesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/solicitacoes': typeof AuthenticatedSolicitacoesRoute
  '/admin/aplicacoes': typeof AuthenticatedAdminAplicacoesRoute
  '/admin/comunicados': typeof AuthenticatedAdminComunicadosRoute
  '/admin/empresas': typeof AuthenticatedAdminEmpresasRoute
  '/aplicacoes/$slug': typeof AuthenticatedAplicacoesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/aplicacoes': typeof AuthenticatedAplicacoesRouteWithChildren
  '/atividades': typeof AuthenticatedAtividadesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/solicitacoes': typeof AuthenticatedSolicitacoesRoute
  '/admin/aplicacoes': typeof AuthenticatedAdminAplicacoesRoute
  '/admin/comunicados': typeof AuthenticatedAdminComunicadosRoute
  '/admin/empresas': typeof AuthenticatedAdminEmpresasRoute
  '/aplicacoes/$slug': typeof AuthenticatedAplicacoesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/aplicacoes': typeof AuthenticatedAplicacoesRouteWithChildren
  '/_authenticated/atividades': typeof AuthenticatedAtividadesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/solicitacoes': typeof AuthenticatedSolicitacoesRoute
  '/_authenticated/admin/aplicacoes': typeof AuthenticatedAdminAplicacoesRoute
  '/_authenticated/admin/comunicados': typeof AuthenticatedAdminComunicadosRoute
  '/_authenticated/admin/empresas': typeof AuthenticatedAdminEmpresasRoute
  '/_authenticated/aplicacoes/$slug': typeof AuthenticatedAplicacoesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/aplicacoes'
    | '/atividades'
    | '/configuracoes'
    | '/dashboard'
    | '/equipe'
    | '/notificacoes'
    | '/perfil'
    | '/solicitacoes'
    | '/admin/aplicacoes'
    | '/admin/comunicados'
    | '/admin/empresas'
    | '/aplicacoes/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/aplicacoes'
    | '/atividades'
    | '/configuracoes'
    | '/dashboard'
    | '/equipe'
    | '/notificacoes'
    | '/perfil'
    | '/solicitacoes'
    | '/admin/aplicacoes'
    | '/admin/comunicados'
    | '/admin/empresas'
    | '/aplicacoes/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/aplicacoes'
    | '/_authenticated/atividades'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/equipe'
    | '/_authenticated/notificacoes'
    | '/_authenticated/perfil'
    | '/_authenticated/solicitacoes'
    | '/_authenticated/admin/aplicacoes'
    | '/_authenticated/admin/comunicados'
    | '/_authenticated/admin/empresas'
    | '/_authenticated/aplicacoes/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/solicitacoes': {
      id: '/_authenticated/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/solicitacoes'
      preLoaderRoute: typeof AuthenticatedSolicitacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atividades': {
      id: '/_authenticated/atividades'
      path: '/atividades'
      fullPath: '/atividades'
      preLoaderRoute: typeof AuthenticatedAtividadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aplicacoes': {
      id: '/_authenticated/aplicacoes'
      path: '/aplicacoes'
      fullPath: '/aplicacoes'
      preLoaderRoute: typeof AuthenticatedAplicacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aplicacoes/$slug': {
      id: '/_authenticated/aplicacoes/$slug'
      path: '/$slug'
      fullPath: '/aplicacoes/$slug'
      preLoaderRoute: typeof AuthenticatedAplicacoesSlugRouteImport
      parentRoute: typeof AuthenticatedAplicacoesRoute
    }
    '/_authenticated/admin/empresas': {
      id: '/_authenticated/admin/empresas'
      path: '/empresas'
      fullPath: '/admin/empresas'
      preLoaderRoute: typeof AuthenticatedAdminEmpresasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/comunicados': {
      id: '/_authenticated/admin/comunicados'
      path: '/comunicados'
      fullPath: '/admin/comunicados'
      preLoaderRoute: typeof AuthenticatedAdminComunicadosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/aplicacoes': {
      id: '/_authenticated/admin/aplicacoes'
      path: '/aplicacoes'
      fullPath: '/admin/aplicacoes'
      preLoaderRoute: typeof AuthenticatedAdminAplicacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAplicacoesRoute: typeof AuthenticatedAdminAplicacoesRoute
  AuthenticatedAdminComunicadosRoute: typeof AuthenticatedAdminComunicadosRoute
  AuthenticatedAdminEmpresasRoute: typeof AuthenticatedAdminEmpresasRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAplicacoesRoute: AuthenticatedAdminAplicacoesRoute,
  AuthenticatedAdminComunicadosRoute: AuthenticatedAdminComunicadosRoute,
  AuthenticatedAdminEmpresasRoute: AuthenticatedAdminEmpresasRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAplicacoesRouteChildren {
  AuthenticatedAplicacoesSlugRoute: typeof AuthenticatedAplicacoesSlugRoute
}

const AuthenticatedAplicacoesRouteChildren: AuthenticatedAplicacoesRouteChildren =
  {
    AuthenticatedAplicacoesSlugRoute: AuthenticatedAplicacoesSlugRoute,
  }

const AuthenticatedAplicacoesRouteWithChildren =
  AuthenticatedAplicacoesRoute._addFileChildren(
    AuthenticatedAplicacoesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAplicacoesRoute: typeof AuthenticatedAplicacoesRouteWithChildren
  AuthenticatedAtividadesRoute: typeof AuthenticatedAtividadesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedSolicitacoesRoute: typeof AuthenticatedSolicitacoesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAplicacoesRoute: AuthenticatedAplicacoesRouteWithChildren,
  AuthenticatedAtividadesRoute: AuthenticatedAtividadesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedSolicitacoesRoute: AuthenticatedSolicitacoesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
